<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0KO5QLA" ignored="0" name="Test" tests="3" failures="1" timestamp="02 Apr 2019 13:45:33 GMT" time="0.081" errors="0">
  <testcase name="enteringcredential" time="0.015" classname="practicetestng.testngpract">
    <failure type="java.lang.AssertionError" message="expected [hello] but found [hi]">
      <![CDATA[java.lang.AssertionError: expected [hello] but found [hi]
at practicetestng.testngpract.enteringcredential(testngpract.java:25)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- enteringcredential -->
  <testcase name="loggedin" time="0.0" classname="practicetestng.testngpract"/>
  <testcase name="openurl" time="0.0" classname="practicetestng.testngpract"/>
</testsuite> <!-- Test -->
